name: Archlinux image Build and Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write  # 必须的权限声明

jobs:
  check-or-create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.set-upload-url.outputs.upload_url }}
    steps:
    - name: Check if Release exists
      id: check-release
      uses: actions/github-script@v6
      env:
        TAG_NAME: ${{ github.ref_name }}  # 使用正确的标签名变量
      with:
        script: |
          try {
            const response = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: process.env.TAG_NAME
            });
            core.setOutput('upload_url', response.data.upload_url);
            return true;
          } catch (error) {
            if (error.status === 404) {
              core.setOutput('upload_url', '');
              return false;
            }
            throw error;
          }

    - name: Create Release if not exists
      if: steps.check-release.outputs.upload_url == ''
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}  # 修正变量名
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Set final upload_url
      id: set-upload-url
      run: |
        if [ "${{ steps.check-release.outputs.upload_url }}" != "" ]; then
          echo "upload_url=${{ steps.check-release.outputs.upload_url }}" >> $GITHUB_OUTPUT
        else
          echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_OUTPUT
        fi

  build-archlinux-k1:
    needs: [check-or-create-release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y git build-essential cpio unzip rsync file bc wget python3 python-is-python3 python3-pip libncurses5-dev libssl-dev dosfstools mtools u-boot-tools flex bison zip xz-utils libconfuse-dev libfdt-dev e2fsprogs squashfs-tools liblz4-tool liblzma-dev gzip tar
    - name: Build
      run: make all
    - name: Upload Asset
      uses: actions/upload-release-asset@v1  # 使用 v1 版本
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.check-or-create-release.outputs.upload_url }}
        asset_path: output/sdcard.img.xz
        asset_name: archlinux-k1-sdcard.img.xz
        asset_content_type: application/zip
    

  